version: "3"

services:
  images-services:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8081:8081"
    restart: always
    container_name: images-services
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure