version: "3"

networks:
  backend:

services:
  auth:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"
    environment:
      JWT_PASS: ${JWT_PASS}
    restart: always
    container_name: auth
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  mongo:
    image: mongo:latest
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  mongo-express:
    image: mongo-express:latest
    restart: always
    networks:
      - backend
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

